-- ============================================================================
-- SEED DATA: Top Indian Landmarks (from Kaggle EDA notebook schema)
-- 30 must-visit landmarks with real coordinates and descriptions
-- ============================================================================

INSERT INTO public.places (name, category, latitude, longitude, address, description, rating, review_count, images, amenities, contact_info, opening_hours, verified) VALUES ('India Gate', 'landmark', 28.614616, 77.231075, 'Delhi, Delhi', '42m war memorial arch commemorating 70,000 Indian soldiers of WWI. Surrounded by lush lawns and the eternal flame (Amar Jawan Jyoti).', 4.6, 0, ARRAY[]::TEXT[], '{"type": "War Memorial", "entrance_fee_inr": 0, "significance": "Historical", "best_time": "Evening", "established": 1921}'::jsonb, '{}'::jsonb, '{"daily": "open"}'::jsonb, true);
INSERT INTO public.places (name, category, latitude, longitude, address, description, rating, review_count, images, amenities, contact_info, opening_hours, verified) VALUES ('Humayun''s Tomb', 'landmark', 28.592207, 77.249105, 'Delhi, Delhi', 'UNESCO World Heritage Mughal garden-tomb. Precursor to the Taj Mahal with Persian-Indian architecture.', 4.5, 0, ARRAY[]::TEXT[], '{"type": "Tomb", "entrance_fee_inr": 30, "significance": "Historical", "best_time": "Afternoon", "established": 1572}'::jsonb, '{}'::jsonb, '{"daily": "open"}'::jsonb, true);
INSERT INTO public.places (name, category, latitude, longitude, address, description, rating, review_count, images, amenities, contact_info, opening_hours, verified) VALUES ('Qutub Minar', 'landmark', 28.523510, 77.186104, 'Delhi, Delhi', '73m UNESCO World Heritage minaret — the tallest brick minaret in the world. Intricate Quran verses carved in sandstone.', 4.5, 0, ARRAY[]::TEXT[], '{"type": "Monument", "entrance_fee_inr": 35, "significance": "Historical", "best_time": "Morning", "established": 1199}'::jsonb, '{}'::jsonb, '{"daily": "open"}'::jsonb, true);
INSERT INTO public.places (name, category, latitude, longitude, address, description, rating, review_count, images, amenities, contact_info, opening_hours, verified) VALUES ('Red Fort', 'landmark', 28.655913, 77.239239, 'Delhi, Delhi', 'Iconic Mughal fort where the PM hoists the flag on Independence Day. UNESCO World Heritage Site with stunning red sandstone walls.', 4.4, 0, ARRAY[]::TEXT[], '{"type": "Fort", "entrance_fee_inr": 35, "significance": "Historical", "best_time": "Morning", "established": 1648}'::jsonb, '{}'::jsonb, '{"daily": "open"}'::jsonb, true);
INSERT INTO public.places (name, category, latitude, longitude, address, description, rating, review_count, images, amenities, contact_info, opening_hours, verified) VALUES ('Lotus Temple', 'temple', 28.553988, 77.257762, 'Delhi, Delhi', 'Bahá''í House of Worship shaped like a lotus flower. Winner of numerous architectural awards.', 4.6, 0, ARRAY[]::TEXT[], '{"type": "Temple", "entrance_fee_inr": 0, "significance": "Religious", "best_time": "Afternoon", "established": 1986}'::jsonb, '{}'::jsonb, '{"daily": "open"}'::jsonb, true);
INSERT INTO public.places (name, category, latitude, longitude, address, description, rating, review_count, images, amenities, contact_info, opening_hours, verified) VALUES ('Taj Mahal', 'landmark', 27.173364, 78.041226, 'Agra, UP', 'UNESCO World Heritage ivory-white marble mausoleum — one of the Seven Wonders of the World. Built by Shah Jahan for Mumtaz.', 4.7, 0, ARRAY[]::TEXT[], '{"type": "Tomb", "entrance_fee_inr": 50, "significance": "Historical", "best_time": "Sunrise", "established": 1653}'::jsonb, '{}'::jsonb, '{"daily": "open"}'::jsonb, true);
INSERT INTO public.places (name, category, latitude, longitude, address, description, rating, review_count, images, amenities, contact_info, opening_hours, verified) VALUES ('Agra Fort', 'landmark', 27.181580, 78.022144, 'Agra, UP', 'UNESCO red sandstone Mughal fort with palatial halls and gardens overlooking the Taj Mahal across the Yamuna.', 4.5, 0, ARRAY[]::TEXT[], '{"type": "Fort", "entrance_fee_inr": 40, "significance": "Historical", "best_time": "Morning", "established": 1573}'::jsonb, '{}'::jsonb, '{"daily": "open"}'::jsonb, true);
INSERT INTO public.places (name, category, latitude, longitude, address, description, rating, review_count, images, amenities, contact_info, opening_hours, verified) VALUES ('Hawa Mahal', 'landmark', 26.922725, 75.825260, 'Jaipur, Rajasthan', 'Palace of Winds — 953 small windows (jharokhas) with intricate latticework. The pink sandstone facade is Jaipur''s most iconic sight.', 4.4, 0, ARRAY[]::TEXT[], '{"type": "Palace", "entrance_fee_inr": 50, "significance": "Historical", "best_time": "Morning", "established": 1799}'::jsonb, '{}'::jsonb, '{"daily": "open"}'::jsonb, true);
INSERT INTO public.places (name, category, latitude, longitude, address, description, rating, review_count, images, amenities, contact_info, opening_hours, verified) VALUES ('City Palace Jaipur', 'landmark', 26.925275, 75.821880, 'Jaipur, Rajasthan', 'Sprawling palace complex blending Rajasthani and Mughal architecture. Home to the world''s largest silver vessels (Guinness record).', 4.5, 0, ARRAY[]::TEXT[], '{"type": "Palace", "entrance_fee_inr": 200, "significance": "Historical", "best_time": "Morning", "established": 1727}'::jsonb, '{}'::jsonb, '{"daily": "open"}'::jsonb, true);
INSERT INTO public.places (name, category, latitude, longitude, address, description, rating, review_count, images, amenities, contact_info, opening_hours, verified) VALUES ('Amer Fort', 'landmark', 26.983768, 75.850346, 'Jaipur, Rajasthan', 'Hilltop fort-palace with ornate mirror-work halls (Sheesh Mahal), courtyards, and elephant rides.', 4.6, 0, ARRAY[]::TEXT[], '{"type": "Fort", "entrance_fee_inr": 100, "significance": "Historical", "best_time": "Morning", "established": 1592}'::jsonb, '{}'::jsonb, '{"daily": "open"}'::jsonb, true);
INSERT INTO public.places (name, category, latitude, longitude, address, description, rating, review_count, images, amenities, contact_info, opening_hours, verified) VALUES ('Gateway of India', 'landmark', 18.922843, 72.833013, 'Mumbai, Maharashtra', 'Basalt arch monument on Mumbai waterfront, built to commemorate King George V''s visit. Overlooks the Arabian Sea.', 4.5, 0, ARRAY[]::TEXT[], '{"type": "Monument", "entrance_fee_inr": 0, "significance": "Historical", "best_time": "Evening", "established": 1924}'::jsonb, '{}'::jsonb, '{"daily": "open"}'::jsonb, true);
INSERT INTO public.places (name, category, latitude, longitude, address, description, rating, review_count, images, amenities, contact_info, opening_hours, verified) VALUES ('Chhatrapati Shivaji Terminus', 'landmark', 18.941375, 72.833745, 'Mumbai, Maharashtra', 'UNESCO World Heritage Gothic-Victorian railway station — still an active terminal serving 3 million commuters daily.', 4.5, 0, ARRAY[]::TEXT[], '{"type": "Railway Station", "entrance_fee_inr": 0, "significance": "Historical", "best_time": "Anytime", "established": 1888}'::jsonb, '{}'::jsonb, '{"daily": "open"}'::jsonb, true);
INSERT INTO public.places (name, category, latitude, longitude, address, description, rating, review_count, images, amenities, contact_info, opening_hours, verified) VALUES ('Elephanta Caves', 'landmark', 18.962655, 72.932359, 'Mumbai, Maharashtra', 'UNESCO rock-cut cave temples on an island in Mumbai harbour. The massive Trimurti Shiva sculpture is 6m high.', 4.4, 0, ARRAY[]::TEXT[], '{"type": "Cave", "entrance_fee_inr": 40, "significance": "Historical", "best_time": "Morning", "established": 500}'::jsonb, '{}'::jsonb, '{"daily": "open"}'::jsonb, true);
INSERT INTO public.places (name, category, latitude, longitude, address, description, rating, review_count, images, amenities, contact_info, opening_hours, verified) VALUES ('Victoria Memorial', 'landmark', 22.545359, 88.344507, 'Kolkata, W Bengal', 'Grand white marble memorial to Queen Victoria. Houses a museum of Indian history and stunning Mughal-era gardens.', 4.5, 0, ARRAY[]::TEXT[], '{"type": "Museum", "entrance_fee_inr": 30, "significance": "Historical", "best_time": "Afternoon", "established": 1921}'::jsonb, '{}'::jsonb, '{"daily": "open"}'::jsonb, true);
INSERT INTO public.places (name, category, latitude, longitude, address, description, rating, review_count, images, amenities, contact_info, opening_hours, verified) VALUES ('Howrah Bridge', 'landmark', 22.587365, 88.345863, 'Kolkata, W Bengal', 'Iconic cantilever bridge over the Hooghly — the busiest in the world carrying 100,000 vehicles and 150,000 pedestrians daily.', 4.4, 0, ARRAY[]::TEXT[], '{"type": "Bridge", "entrance_fee_inr": 0, "significance": "Historical", "best_time": "Evening", "established": 1943}'::jsonb, '{}'::jsonb, '{"daily": "open"}'::jsonb, true);
INSERT INTO public.places (name, category, latitude, longitude, address, description, rating, review_count, images, amenities, contact_info, opening_hours, verified) VALUES ('Golconda Fort', 'landmark', 17.384074, 78.399994, 'Hyderabad, Telangana', 'Medieval fort famous for its acoustic architecture — a hand clap at the entrance is heard at the hilltop. Former diamond trading center.', 4.5, 0, ARRAY[]::TEXT[], '{"type": "Fort", "entrance_fee_inr": 25, "significance": "Historical", "best_time": "Morning", "established": 1143}'::jsonb, '{}'::jsonb, '{"daily": "open"}'::jsonb, true);
INSERT INTO public.places (name, category, latitude, longitude, address, description, rating, review_count, images, amenities, contact_info, opening_hours, verified) VALUES ('Charminar', 'landmark', 17.363486, 78.474944, 'Hyderabad, Telangana', 'Iconic four-minaret mosque-monument at the heart of old Hyderabad. Surrounded by the famous Laad Bazaar bangles market.', 4.3, 0, ARRAY[]::TEXT[], '{"type": "Monument", "entrance_fee_inr": 25, "significance": "Historical", "best_time": "Evening", "established": 1591}'::jsonb, '{}'::jsonb, '{"daily": "open"}'::jsonb, true);
INSERT INTO public.places (name, category, latitude, longitude, address, description, rating, review_count, images, amenities, contact_info, opening_hours, verified) VALUES ('Mysore Palace', 'landmark', 12.305358, 76.654399, 'Mysore, Karnataka', 'Indo-Saracenic palace illuminated by 97,000 bulbs on Sundays and Dasara. One of India''s most visited palaces.', 4.6, 0, ARRAY[]::TEXT[], '{"type": "Palace", "entrance_fee_inr": 70, "significance": "Historical", "best_time": "Evening", "established": 1912}'::jsonb, '{}'::jsonb, '{"daily": "open"}'::jsonb, true);
INSERT INTO public.places (name, category, latitude, longitude, address, description, rating, review_count, images, amenities, contact_info, opening_hours, verified) VALUES ('Hampi Ruins', 'landmark', 15.333275, 76.459760, 'Hampi, Karnataka', 'UNESCO ruins of the Vijayanagara Empire spread across 26 sq km. Over 1,600 surviving structures — temples, markets, aqueducts.', 4.7, 0, ARRAY[]::TEXT[], '{"type": "Archaeological", "entrance_fee_inr": 40, "significance": "Historical", "best_time": "Morning", "established": 1336}'::jsonb, '{}'::jsonb, '{"daily": "open"}'::jsonb, true);
INSERT INTO public.places (name, category, latitude, longitude, address, description, rating, review_count, images, amenities, contact_info, opening_hours, verified) VALUES ('Konark Sun Temple', 'temple', 19.889197, 86.093290, 'Konark, Odisha', 'UNESCO World Heritage 13th-century temple shaped as a massive chariot with 24 intricately carved stone wheels.', 4.6, 0, ARRAY[]::TEXT[], '{"type": "Temple", "entrance_fee_inr": 40, "significance": "Historical", "best_time": "Sunrise", "established": 1250}'::jsonb, '{}'::jsonb, '{"daily": "open"}'::jsonb, true);
INSERT INTO public.places (name, category, latitude, longitude, address, description, rating, review_count, images, amenities, contact_info, opening_hours, verified) VALUES ('Sanchi Stupa', 'temple', 23.478918, 77.740374, 'Sanchi, MP', 'UNESCO oldest stone structure in India, commissioned by Emperor Ashoka. Elaborate gateway carvings depict the life of Buddha.', 4.5, 0, ARRAY[]::TEXT[], '{"type": "Stupa", "entrance_fee_inr": 30, "significance": "Religious", "best_time": "Morning"}'::jsonb, '{}'::jsonb, '{"daily": "open"}'::jsonb, true);
INSERT INTO public.places (name, category, latitude, longitude, address, description, rating, review_count, images, amenities, contact_info, opening_hours, verified) VALUES ('Khajuraho Temples', 'temple', 24.830013, 79.921380, 'Khajuraho, MP', 'UNESCO World Heritage temples famous for erotic sculptures. Built by the Chandela dynasty over 200 years.', 4.6, 0, ARRAY[]::TEXT[], '{"type": "Temple", "entrance_fee_inr": 40, "significance": "Historical", "best_time": "Morning", "established": 950}'::jsonb, '{}'::jsonb, '{"daily": "open"}'::jsonb, true);
INSERT INTO public.places (name, category, latitude, longitude, address, description, rating, review_count, images, amenities, contact_info, opening_hours, verified) VALUES ('Ajanta Caves', 'landmark', 20.551488, 75.703036, 'Aurangabad, Maharashtra', 'UNESCO 30 rock-cut Buddhist caves with stunning 2nd-century murals — the finest surviving examples of ancient Indian painting.', 4.6, 0, ARRAY[]::TEXT[], '{"type": "Cave", "entrance_fee_inr": 40, "significance": "Historical", "best_time": "Morning"}'::jsonb, '{}'::jsonb, '{"daily": "open"}'::jsonb, true);
INSERT INTO public.places (name, category, latitude, longitude, address, description, rating, review_count, images, amenities, contact_info, opening_hours, verified) VALUES ('Ellora Caves', 'landmark', 20.026479, 75.179424, 'Aurangabad, Maharashtra', 'UNESCO 34 caves spanning Buddhist, Hindu, and Jain art. The monolithic Kailasa Temple is carved from a single rock — larger than the Parthenon.', 4.6, 0, ARRAY[]::TEXT[], '{"type": "Cave", "entrance_fee_inr": 40, "significance": "Historical", "best_time": "Morning", "established": 600}'::jsonb, '{}'::jsonb, '{"daily": "open"}'::jsonb, true);
INSERT INTO public.places (name, category, latitude, longitude, address, description, rating, review_count, images, amenities, contact_info, opening_hours, verified) VALUES ('Brihadeeswarar Temple', 'temple', 10.781244, 79.131912, 'Thanjavur, TN', 'UNESCO Chola-era temple with a 66m vimana tower — the tallest in the world. The shadow of the dome never falls on the ground.', 4.7, 0, ARRAY[]::TEXT[], '{"type": "Temple", "entrance_fee_inr": 0, "significance": "Religious", "best_time": "Morning", "established": 1010}'::jsonb, '{}'::jsonb, '{"daily": "open"}'::jsonb, true);
INSERT INTO public.places (name, category, latitude, longitude, address, description, rating, review_count, images, amenities, contact_info, opening_hours, verified) VALUES ('Mahabodhi Temple', 'temple', 24.697887, 84.991917, 'Bodh Gaya, Bihar', 'UNESCO World Heritage site where Gautama Buddha attained enlightenment under the Bodhi Tree. Holiest site in Buddhism.', 4.7, 0, ARRAY[]::TEXT[], '{"type": "Temple", "entrance_fee_inr": 0, "significance": "Religious", "best_time": "Morning"}'::jsonb, '{}'::jsonb, '{"daily": "open"}'::jsonb, true);
INSERT INTO public.places (name, category, latitude, longitude, address, description, rating, review_count, images, amenities, contact_info, opening_hours, verified) VALUES ('Jantar Mantar Jaipur', 'landmark', 26.926276, 75.824577, 'Jaipur, Rajasthan', 'UNESCO collection of 19 astronomical instruments including the world''s largest stone sundial (27m tall).', 4.3, 0, ARRAY[]::TEXT[], '{"type": "Observatory", "entrance_fee_inr": 50, "significance": "Scientific", "best_time": "Morning", "established": 1734}'::jsonb, '{}'::jsonb, '{"daily": "open"}'::jsonb, true);
INSERT INTO public.places (name, category, latitude, longitude, address, description, rating, review_count, images, amenities, contact_info, opening_hours, verified) VALUES ('Fatehpur Sikri', 'landmark', 27.093844, 77.659338, 'Agra, UP', 'UNESCO Mughal ghost city built by Akbar. Abandoned after 14 years due to water scarcity. Buland Darwaza is 54m high.', 4.5, 0, ARRAY[]::TEXT[], '{"type": "Fort", "entrance_fee_inr": 40, "significance": "Historical", "best_time": "Morning", "established": 1571}'::jsonb, '{}'::jsonb, '{"daily": "open"}'::jsonb, true);
INSERT INTO public.places (name, category, latitude, longitude, address, description, rating, review_count, images, amenities, contact_info, opening_hours, verified) VALUES ('Meenakshi Temple', 'temple', 9.921219, 78.118223, 'Madurai, TN', '14 towering gopurams covered in thousands of colorful sculptures. The Hall of 1000 Pillars and Golden Lotus Tank are iconic.', 4.7, 0, ARRAY[]::TEXT[], '{"type": "Temple", "entrance_fee_inr": 0, "significance": "Religious", "best_time": "Morning", "established": 1623}'::jsonb, '{}'::jsonb, '{"daily": "open"}'::jsonb, true);
INSERT INTO public.places (name, category, latitude, longitude, address, description, rating, review_count, images, amenities, contact_info, opening_hours, verified) VALUES ('Rock Garden Chandigarh', 'landmark', 30.753377, 76.806223, 'Chandigarh, Chandigarh', '18-acre sculpture garden created from industrial and urban waste by Nek Chand. Over 5,000 recycled art sculptures.', 4.3, 0, ARRAY[]::TEXT[], '{"type": "Park", "entrance_fee_inr": 30, "significance": "Environmental", "best_time": "Afternoon", "established": 1957}'::jsonb, '{}'::jsonb, '{"daily": "open"}'::jsonb, true);
