import React, { createContext, useContext, useState, ReactNode } from "react";

export type Language = "en" | "hi" | "ta" | "te" | "kn" | "ml" | "bn" | "mr";

interface Translations {
  // Common
  home: string;
  explore: string;
  trips: string;
  profile: string;
  search: string;
  filter: string;
  cancel: string;
  save: string;
  add: string;
  delete: string;
  edit: string;
  back: string;
  viewAll: string;
  loading: string;
  
  // Home
  goodMorning: string;
  goodAfternoon: string;
  goodEvening: string;
  traveler: string;
  whereExplore: string;
  liveLocation: string;
  sharingLocation: string;
  locationOff: string;
  exploreCategories: string;
  exploreMap: string;
  planTrip: string;
  discover: string;
  
  // Categories
  temples: string;
  hospitals: string;
  emergency: string;
  hiddenSpots: string;
  hiddenSpotsDesc: string;
  transport: string;
  hostels: string;
  attractions: string;
  
  // SOS
  sos: string;
  tapForEmergency: string;
  confirmEmergency: string;
  sendingAlert: string;
  alertSent: string;
  sosDescription: string;
  sendSOS: string;
  
  // Booking
  booking: string;
  bookNow: string;
  searchPlaces: string;
  priceRange: string;
  rating: string;
  distance: string;
  sortBy: string;
  bestMatch: string;
  cheapest: string;
  safest: string;
  nearestFirst: string;
  available: string;
  perNight: string;
  perPerson: string;
  viewOnMap: string;
  listView: string;
  mapView: string;
  
  // Profile
  myProfile: string;
  emergencyContacts: string;
  sosAlertRecipients: string;
  addNewContact: string;
  name: string;
  phone: string;
  relation: string;
  primary: string;
  language: string;
  settings: string;
  helpSupport: string;
  logout: string;
  
  // Trip Planner
  tripPlanner: string;
  fromLocation: string;
  destination: string;
  budget: string;
  days: string;
  day: string;
  generateItinerary: string;
  transportMode: string;
  stays: string;
  food: string;
  activities: string;
  buffer: string;
  total: string;
  budgetBreakdown: string;
  
  // Voice
  voiceAssistant: string;
  listeningCommands: string;
}

const translations: Record<Language, Translations> = {
  en: {
    home: "Home",
    explore: "Explore",
    trips: "Trips",
    profile: "Profile",
    search: "Search",
    filter: "Filter",
    cancel: "Cancel",
    save: "Save",
    add: "Add",
    delete: "Delete",
    edit: "Edit",
    back: "Back",
    viewAll: "View All",
    loading: "Loading...",
    goodMorning: "Good Morning",
    goodAfternoon: "Good Afternoon",
    goodEvening: "Good Evening",
    traveler: "Traveler",
    whereExplore: "Where would you like to explore today?",
    liveLocation: "Live Location",
    sharingLocation: "Sharing your location",
    locationOff: "Location off",
    exploreCategories: "Explore Categories",
    exploreMap: "Explore Map",
    planTrip: "Plan Trip",
    discover: "Discover",
    temples: "Temples",
    hospitals: "Hospitals",
    emergency: "Emergency",
    hiddenSpots: "Hidden Spots",
    hiddenSpotsDesc: "Local gems, non-commercial places",
    transport: "Transport",
    hostels: "Hostels",
    attractions: "Attractions",
    sos: "SOS",
    tapForEmergency: "Tap for Emergency",
    confirmEmergency: "Confirm Emergency SOS?",
    sendingAlert: "Sending alert...",
    alertSent: "Alert Sent!",
    sosDescription: "This will send your live location to emergency services and your registered contacts.",
    sendSOS: "Send SOS",
    booking: "Booking",
    bookNow: "Book Now",
    searchPlaces: "Search places, attractions...",
    priceRange: "Price Range",
    rating: "Rating",
    distance: "Distance",
    sortBy: "Sort By",
    bestMatch: "Best Match",
    cheapest: "Cheapest",
    safest: "Safest",
    nearestFirst: "Nearest First",
    available: "Available",
    perNight: "per night",
    perPerson: "per person",
    viewOnMap: "View on Map",
    listView: "List View",
    mapView: "Map View",
    myProfile: "My Profile",
    emergencyContacts: "Emergency Contacts",
    sosAlertRecipients: "SOS alert recipients",
    addNewContact: "Add New Contact",
    name: "Name",
    phone: "Phone",
    relation: "Relation",
    primary: "Primary",
    language: "Language",
    settings: "Settings",
    helpSupport: "Help & Support",
    logout: "Logout",
    tripPlanner: "Trip Planner",
    fromLocation: "From Location",
    destination: "Destination",
    budget: "Budget",
    days: "Days",
    day: "Day",
    generateItinerary: "Generate Itinerary",
    transportMode: "Transport Mode",
    stays: "Stays",
    food: "Food",
    activities: "Activities",
    buffer: "Buffer",
    total: "Total",
    budgetBreakdown: "Budget Breakdown",
    voiceAssistant: "Voice Assistant",
    listeningCommands: "Listening for commands...",
  },
  hi: {
    home: "होम",
    explore: "खोजें",
    trips: "यात्राएं",
    profile: "प्रोफ़ाइल",
    search: "खोजें",
    filter: "फ़िल्टर",
    cancel: "रद्द करें",
    save: "सहेजें",
    add: "जोड़ें",
    delete: "हटाएं",
    edit: "संपादित करें",
    back: "वापस",
    viewAll: "सभी देखें",
    loading: "लोड हो रहा है...",
    goodMorning: "सुप्रभात",
    goodAfternoon: "शुभ दोपहर",
    goodEvening: "शुभ संध्या",
    traveler: "यात्री",
    whereExplore: "आज आप कहाँ जाना चाहेंगे?",
    liveLocation: "लाइव लोकेशन",
    sharingLocation: "आपकी लोकेशन शेयर हो रही है",
    locationOff: "लोकेशन बंद",
    exploreCategories: "श्रेणियां खोजें",
    exploreMap: "मानचित्र देखें",
    planTrip: "यात्रा की योजना",
    discover: "खोजें",
    temples: "मंदिर",
    hospitals: "अस्पताल",
    emergency: "आपातकालीन",
    hiddenSpots: "छुपे स्थान",
    hiddenSpotsDesc: "स्थानीय रत्न, गैर-व्यावसायिक स्थान",
    transport: "परिवहन",
    hostels: "होस्टल",
    attractions: "आकर्षण",
    sos: "SOS",
    tapForEmergency: "आपातकाल के लिए टैप करें",
    confirmEmergency: "आपातकालीन SOS की पुष्टि करें?",
    sendingAlert: "अलर्ट भेजा जा रहा है...",
    alertSent: "अलर्ट भेजा गया!",
    sosDescription: "यह आपकी लाइव लोकेशन आपातकालीन सेवाओं और आपके संपर्कों को भेजेगा।",
    sendSOS: "SOS भेजें",
    booking: "बुकिंग",
    bookNow: "अभी बुक करें",
    searchPlaces: "स्थान, आकर्षण खोजें...",
    priceRange: "मूल्य सीमा",
    rating: "रेटिंग",
    distance: "दूरी",
    sortBy: "क्रमबद्ध करें",
    bestMatch: "सबसे अच्छा",
    cheapest: "सबसे सस्ता",
    safest: "सबसे सुरक्षित",
    nearestFirst: "निकटतम पहले",
    available: "उपलब्ध",
    perNight: "प्रति रात",
    perPerson: "प्रति व्यक्ति",
    viewOnMap: "मानचित्र पर देखें",
    listView: "सूची दृश्य",
    mapView: "मानचित्र दृश्य",
    myProfile: "मेरी प्रोफ़ाइल",
    emergencyContacts: "आपातकालीन संपर्क",
    sosAlertRecipients: "SOS अलर्ट प्राप्तकर्ता",
    addNewContact: "नया संपर्क जोड़ें",
    name: "नाम",
    phone: "फ़ोन",
    relation: "संबंध",
    primary: "प्राथमिक",
    language: "भाषा",
    settings: "सेटिंग्स",
    helpSupport: "सहायता और समर्थन",
    logout: "लॉगआउट",
    tripPlanner: "यात्रा योजनाकार",
    fromLocation: "से स्थान",
    destination: "गंतव्य",
    budget: "बजट",
    days: "दिन",
    day: "दिन",
    generateItinerary: "यात्रा कार्यक्रम बनाएं",
    transportMode: "परिवहन मोड",
    stays: "रहने की जगह",
    food: "भोजन",
    activities: "गतिविधियां",
    buffer: "बफर",
    total: "कुल",
    budgetBreakdown: "बजट विवरण",
    voiceAssistant: "वॉइस असिस्टेंट",
    listeningCommands: "कमांड सुन रहा है...",
  },
  ta: {
    home: "முகப்பு",
    explore: "ஆராய்க",
    trips: "பயணங்கள்",
    profile: "சுயவிவரம்",
    search: "தேடு",
    filter: "வடிகட்டி",
    cancel: "ரத்து",
    save: "சேமி",
    add: "சேர்",
    delete: "நீக்கு",
    edit: "திருத்து",
    back: "பின்",
    viewAll: "அனைத்தும் காண",
    loading: "ஏற்றுகிறது...",
    goodMorning: "காலை வணக்கம்",
    goodAfternoon: "மதிய வணக்கம்",
    goodEvening: "மாலை வணக்கம்",
    traveler: "பயணி",
    whereExplore: "இன்று எங்கு செல்ல விரும்புகிறீர்கள்?",
    liveLocation: "நேரடி இருப்பிடம்",
    sharingLocation: "உங்கள் இருப்பிடம் பகிரப்படுகிறது",
    locationOff: "இருப்பிடம் அணைப்பு",
    exploreCategories: "வகைகளை ஆராய்க",
    exploreMap: "வரைபடம் பார்",
    planTrip: "பயணம் திட்டமிடு",
    discover: "கண்டறி",
    temples: "கோயில்கள்",
    hospitals: "மருத்துவமனைகள்",
    emergency: "அவசரநிலை",
    hiddenSpots: "மறைந்த இடங்கள்",
    hiddenSpotsDesc: "உள்ளூர் ரத்தினங்கள், வணிகமற்ற இடங்கள்",
    transport: "போக்குவரத்து",
    hostels: "விடுதிகள்",
    attractions: "சுற்றுலா",
    sos: "SOS",
    tapForEmergency: "அவசரத்திற்கு தட்டவும்",
    confirmEmergency: "அவசர SOS உறுதிப்படுத்தவா?",
    sendingAlert: "எச்சரிக்கை அனுப்புகிறது...",
    alertSent: "எச்சரிக்கை அனுப்பப்பட்டது!",
    sosDescription: "இது உங்கள் நேரடி இருப்பிடத்தை அவசர சேவைகளுக்கு அனுப்பும்.",
    sendSOS: "SOS அனுப்பு",
    booking: "முன்பதிவு",
    bookNow: "இப்போது புக்",
    searchPlaces: "இடங்கள், சுற்றுலா தேடு...",
    priceRange: "விலை வரம்பு",
    rating: "மதிப்பீடு",
    distance: "தூரம்",
    sortBy: "வரிசைப்படுத்து",
    bestMatch: "சிறந்த பொருத்தம்",
    cheapest: "மலிவானது",
    safest: "பாதுகாப்பானது",
    nearestFirst: "அருகிலுள்ளது முதலில்",
    available: "கிடைக்கும்",
    perNight: "இரவுக்கு",
    perPerson: "நபருக்கு",
    viewOnMap: "வரைபடத்தில் பார்",
    listView: "பட்டியல்",
    mapView: "வரைபடம்",
    myProfile: "என் சுயவிவரம்",
    emergencyContacts: "அவசர தொடர்புகள்",
    sosAlertRecipients: "SOS எச்சரிக்கை பெறுநர்கள்",
    addNewContact: "புதிய தொடர்பு சேர்",
    name: "பெயர்",
    phone: "தொலைபேசி",
    relation: "உறவு",
    primary: "முதன்மை",
    language: "மொழி",
    settings: "அமைப்புகள்",
    helpSupport: "உதவி & ஆதரவு",
    logout: "வெளியேறு",
    tripPlanner: "பயண திட்டமிடுபவர்",
    fromLocation: "இருந்து",
    destination: "இடம்",
    budget: "பட்ஜெட்",
    days: "நாட்கள்",
    day: "நாள்",
    generateItinerary: "பயணத் திட்டம் உருவாக்கு",
    transportMode: "போக்குவரத்து முறை",
    stays: "தங்குமிடங்கள்",
    food: "உணவு",
    activities: "செயல்பாடுகள்",
    buffer: "இடையகம்",
    total: "மொத்தம்",
    budgetBreakdown: "பட்ஜெட் விவரம்",
    voiceAssistant: "குரல் உதவியாளர்",
    listeningCommands: "கட்டளைகளைக் கேட்கிறது...",
  },
  te: {
    home: "హోమ్",
    explore: "అన్వేషించు",
    trips: "ప్రయాణాలు",
    profile: "ప్రొఫైల్",
    search: "శోధించు",
    filter: "ఫిల్టర్",
    cancel: "రద్దు",
    save: "సేవ్",
    add: "జోడించు",
    delete: "తొలగించు",
    edit: "సవరించు",
    back: "వెనుకకు",
    viewAll: "అన్నీ చూడు",
    loading: "లోడ్ అవుతోంది...",
    goodMorning: "శుభోదయం",
    goodAfternoon: "శుభ మధ్యాహ్నం",
    goodEvening: "శుభ సాయంత్రం",
    traveler: "యాత్రికుడు",
    whereExplore: "ఈరోజు ఎక్కడికి వెళ్ళాలనుకుంటున్నారు?",
    liveLocation: "లైవ్ లొకేషన్",
    sharingLocation: "మీ లొకేషన్ షేర్ అవుతోంది",
    locationOff: "లొకేషన్ ఆఫ్",
    exploreCategories: "వర్గాలు అన్వేషించు",
    exploreMap: "మ్యాప్ చూడు",
    planTrip: "ప్రయాణం ప్లాన్",
    discover: "కనుగొను",
    temples: "దేవాలయాలు",
    hospitals: "ఆసుపత్రులు",
    emergency: "అత్యవసర",
    hiddenSpots: "దాచిన ప్రదేశాలు",
    hiddenSpotsDesc: "స్థానిక రత్నాలు, వాణిజ్యేతర ప్రదేశాలు",
    transport: "రవాణా",
    hostels: "హాస్టల్స్",
    attractions: "ఆకర్షణలు",
    sos: "SOS",
    tapForEmergency: "అత్యవసర కోసం ట్యాప్",
    confirmEmergency: "అత్యవసర SOS నిర్ధారించు?",
    sendingAlert: "అలర్ట్ పంపుతోంది...",
    alertSent: "అలర్ట్ పంపబడింది!",
    sosDescription: "ఇది మీ లైవ్ లొకేషన్‌ను అత్యవసర సేవలకు పంపుతుంది.",
    sendSOS: "SOS పంపు",
    booking: "బుకింగ్",
    bookNow: "ఇప్పుడే బుక్",
    searchPlaces: "ప్రదేశాలు, ఆకర్షణలు శోధించు...",
    priceRange: "ధర పరిధి",
    rating: "రేటింగ్",
    distance: "దూరం",
    sortBy: "క్రమబద్ధీకరించు",
    bestMatch: "ఉత్తమ మ్యాచ్",
    cheapest: "చవకైనది",
    safest: "సురక్షితమైనది",
    nearestFirst: "సమీపంలోనివి ముందు",
    available: "అందుబాటులో",
    perNight: "రాత్రికి",
    perPerson: "వ్యక్తికి",
    viewOnMap: "మ్యాప్‌లో చూడు",
    listView: "జాబితా వీక్షణ",
    mapView: "మ్యాప్ వీక్షణ",
    myProfile: "నా ప్రొఫైల్",
    emergencyContacts: "అత్యవసర సంప్రదింపులు",
    sosAlertRecipients: "SOS అలర్ట్ స్వీకర్తలు",
    addNewContact: "కొత్త సంప్రదింపు జోడించు",
    name: "పేరు",
    phone: "ఫోన్",
    relation: "సంబంధం",
    primary: "ప్రాథమిక",
    language: "భాష",
    settings: "సెట్టింగ్స్",
    helpSupport: "సహాయం & మద్దతు",
    logout: "లాగ్ అవుట్",
    tripPlanner: "ప్రయాణ ప్లానర్",
    fromLocation: "నుండి",
    destination: "గమ్యస్థానం",
    budget: "బడ్జెట్",
    days: "రోజులు",
    day: "రోజు",
    generateItinerary: "మార్గసూచి రూపొందించు",
    transportMode: "రవాణా మోడ్",
    stays: "బస",
    food: "భోజనం",
    activities: "కార్యకలాపాలు",
    buffer: "బఫర్",
    total: "మొత్తం",
    budgetBreakdown: "బడ్జెట్ వివరాలు",
    voiceAssistant: "వాయిస్ అసిస్టెంట్",
    listeningCommands: "ఆదేశాలు వింటోంది...",
  },
  kn: {
    home: "ಮುಖಪುಟ",
    explore: "ಅನ್ವೇಷಿಸಿ",
    trips: "ಪ್ರವಾಸಗಳು",
    profile: "ಪ್ರೊಫೈಲ್",
    search: "ಹುಡುಕಿ",
    filter: "ಫಿಲ್ಟರ್",
    cancel: "ರದ್ದುಮಾಡಿ",
    save: "ಉಳಿಸಿ",
    add: "ಸೇರಿಸಿ",
    delete: "ಅಳಿಸಿ",
    edit: "ಸಂಪಾದಿಸಿ",
    back: "ಹಿಂದೆ",
    viewAll: "ಎಲ್ಲಾ ವೀಕ್ಷಿಸಿ",
    loading: "ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    goodMorning: "ಶುಭೋದಯ",
    goodAfternoon: "ಶುಭ ಮಧ್ಯಾಹ್ನ",
    goodEvening: "ಶುಭ ಸಂಜೆ",
    traveler: "ಪ್ರಯಾಣಿಕ",
    whereExplore: "ಇಂದು ಎಲ್ಲಿಗೆ ಹೋಗಲು ಬಯಸುತ್ತೀರಿ?",
    liveLocation: "ಲೈವ್ ಸ್ಥಳ",
    sharingLocation: "ನಿಮ್ಮ ಸ್ಥಳವನ್ನು ಹಂಚಿಕೊಳ್ಳಲಾಗುತ್ತಿದೆ",
    locationOff: "ಸ್ಥಳ ಆಫ್",
    exploreCategories: "ವರ್ಗಗಳನ್ನು ಅನ್ವೇಷಿಸಿ",
    exploreMap: "ನಕ್ಷೆ ವೀಕ್ಷಿಸಿ",
    planTrip: "ಪ್ರವಾಸ ಯೋಜಿಸಿ",
    discover: "ಅನ್ವೇಷಿಸಿ",
    temples: "ದೇವಸ್ಥಾನಗಳು",
    hospitals: "ಆಸ್ಪತ್ರೆಗಳು",
    emergency: "ತುರ್ತು",
    hiddenSpots: "ಅಡಗಿದ ಸ್ಥಳಗಳು",
    hiddenSpotsDesc: "ಸ್ಥಳೀಯ ರತ್ನಗಳು, ವಾಣಿಜ್ಯೇತರ ಸ್ಥಳಗಳು",
    transport: "ಸಾರಿಗೆ",
    hostels: "ಹಾಸ್ಟೆಲ್‌ಗಳು",
    attractions: "ಆಕರ್ಷಣೆಗಳು",
    sos: "SOS",
    tapForEmergency: "ತುರ್ತು ಸಂದರ್ಭಕ್ಕೆ ಟ್ಯಾಪ್ ಮಾಡಿ",
    confirmEmergency: "ತುರ್ತು SOS ದೃಢೀಕರಿಸಿ?",
    sendingAlert: "ಎಚ್ಚರಿಕೆ ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ...",
    alertSent: "ಎಚ್ಚರಿಕೆ ಕಳುಹಿಸಲಾಗಿದೆ!",
    sosDescription: "ಇದು ನಿಮ್ಮ ಲೈವ್ ಸ್ಥಳವನ್ನು ತುರ್ತು ಸೇವೆಗಳಿಗೆ ಕಳುಹಿಸುತ್ತದೆ.",
    sendSOS: "SOS ಕಳುಹಿಸಿ",
    booking: "ಬುಕಿಂಗ್",
    bookNow: "ಈಗ ಬುಕ್ ಮಾಡಿ",
    searchPlaces: "ಸ್ಥಳಗಳು, ಆಕರ್ಷಣೆಗಳನ್ನು ಹುಡುಕಿ...",
    priceRange: "ಬೆಲೆ ವ್ಯಾಪ್ತಿ",
    rating: "ರೇಟಿಂಗ್",
    distance: "ದೂರ",
    sortBy: "ವಿಂಗಡಿಸಿ",
    bestMatch: "ಉತ್ತಮ ಹೊಂದಾಣಿಕೆ",
    cheapest: "ಅಗ್ಗದ",
    safest: "ಸುರಕ್ಷಿತ",
    nearestFirst: "ಸಮೀಪದವು ಮೊದಲು",
    available: "ಲಭ್ಯವಿದೆ",
    perNight: "ರಾತ್ರಿಗೆ",
    perPerson: "ವ್ಯಕ್ತಿಗೆ",
    viewOnMap: "ನಕ್ಷೆಯಲ್ಲಿ ವೀಕ್ಷಿಸಿ",
    listView: "ಪಟ್ಟಿ ವೀಕ್ಷಣೆ",
    mapView: "ನಕ್ಷೆ ವೀಕ್ಷಣೆ",
    myProfile: "ನನ್ನ ಪ್ರೊಫೈಲ್",
    emergencyContacts: "ತುರ್ತು ಸಂಪರ್ಕಗಳು",
    sosAlertRecipients: "SOS ಎಚ್ಚರಿಕೆ ಸ್ವೀಕರಿಸುವವರು",
    addNewContact: "ಹೊಸ ಸಂಪರ್ಕ ಸೇರಿಸಿ",
    name: "ಹೆಸರು",
    phone: "ಫೋನ್",
    relation: "ಸಂಬಂಧ",
    primary: "ಪ್ರಾಥಮಿಕ",
    language: "ಭಾಷೆ",
    settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    helpSupport: "ಸಹಾಯ & ಬೆಂಬಲ",
    logout: "ಲಾಗ್ ಔಟ್",
    tripPlanner: "ಪ್ರವಾಸ ಯೋಜಕ",
    fromLocation: "ಇಂದ",
    destination: "ಗಮ್ಯಸ್ಥಾನ",
    budget: "ಬಜೆಟ್",
    days: "ದಿನಗಳು",
    day: "ದಿನ",
    generateItinerary: "ಮಾರ್ಗಸೂಚಿ ರಚಿಸಿ",
    transportMode: "ಸಾರಿಗೆ ಮೋಡ್",
    stays: "ವಾಸ್ತವ್ಯ",
    food: "ಆಹಾರ",
    activities: "ಚಟುವಟಿಕೆಗಳು",
    buffer: "ಬಫರ್",
    total: "ಒಟ್ಟು",
    budgetBreakdown: "ಬಜೆಟ್ ವಿವರ",
    voiceAssistant: "ಧ್ವನಿ ಸಹಾಯಕ",
    listeningCommands: "ಆದೇಶಗಳನ್ನು ಕೇಳಲಾಗುತ್ತಿದೆ...",
  },
  ml: {
    home: "ഹോം",
    explore: "പര്യവേക്ഷണം",
    trips: "യാത്രകൾ",
    profile: "പ്രൊഫൈൽ",
    search: "തിരയുക",
    filter: "ഫിൽട്ടർ",
    cancel: "റദ്ദാക്കുക",
    save: "സേവ്",
    add: "ചേർക്കുക",
    delete: "ഇല്ലാതാക്കുക",
    edit: "എഡിറ്റ്",
    back: "തിരികെ",
    viewAll: "എല്ലാം കാണുക",
    loading: "ലോഡ് ചെയ്യുന്നു...",
    goodMorning: "സുപ്രഭാതം",
    goodAfternoon: "ശുഭ ഉച്ച",
    goodEvening: "ശുഭ സായാഹ്നം",
    traveler: "യാത്രികൻ",
    whereExplore: "ഇന്ന് എവിടേക്ക് പോകണം?",
    liveLocation: "ലൈവ് ലൊക്കേഷൻ",
    sharingLocation: "നിങ്ങളുടെ ലൊക്കേഷൻ പങ്കിടുന്നു",
    locationOff: "ലൊക്കേഷൻ ഓഫ്",
    exploreCategories: "വിഭാഗങ്ങൾ കണ്ടെത്തുക",
    exploreMap: "മാപ്പ് കാണുക",
    planTrip: "യാത്ര ആസൂത്രണം",
    discover: "കണ്ടെത്തുക",
    temples: "ക്ഷേത്രങ്ങൾ",
    hospitals: "ആശുപത്രികൾ",
    emergency: "അടിയന്തിരം",
    hiddenSpots: "രഹസ്യ സ്ഥലങ്ങൾ",
    hiddenSpotsDesc: "പ്രാദേശിക രത്നങ്ങൾ, വാണിജ്യേതര സ്ഥലങ്ങൾ",
    transport: "ഗതാഗതം",
    hostels: "ഹോസ്റ്റലുകൾ",
    attractions: "ആകർഷണങ്ങൾ",
    sos: "SOS",
    tapForEmergency: "അടിയന്തിര സഹായത്തിന് ടാപ്പ് ചെയ്യുക",
    confirmEmergency: "അടിയന്തിര SOS സ്ഥിരീകരിക്കണോ?",
    sendingAlert: "അലേർട്ട് അയക്കുന്നു...",
    alertSent: "അലേർട്ട് അയച്ചു!",
    sosDescription: "ഇത് നിങ്ങളുടെ ലൈവ് ലൊക്കേഷൻ അടിയന്തിര സേവനങ്ങൾക്ക് അയക്കും.",
    sendSOS: "SOS അയക്കുക",
    booking: "ബുക്കിംഗ്",
    bookNow: "ഇപ്പോൾ ബുക്ക് ചെയ്യുക",
    searchPlaces: "സ്ഥലങ്ങൾ, ആകർഷണങ്ങൾ തിരയുക...",
    priceRange: "വില പരിധി",
    rating: "റേറ്റിംഗ്",
    distance: "ദൂരം",
    sortBy: "ക്രമീകരിക്കുക",
    bestMatch: "മികച്ച പൊരുത്തം",
    cheapest: "ഏറ്റവും വിലകുറഞ്ഞത്",
    safest: "ഏറ്റവും സുരക്ഷിതം",
    nearestFirst: "അടുത്തത് ആദ്യം",
    available: "ലഭ്യമാണ്",
    perNight: "ഓരോ രാത്രിയിലും",
    perPerson: "ഓരോ ആൾക്കും",
    viewOnMap: "മാപ്പിൽ കാണുക",
    listView: "ലിസ്റ്റ് വ്യൂ",
    mapView: "മാപ്പ് വ്യൂ",
    myProfile: "എന്റെ പ്രൊഫൈൽ",
    emergencyContacts: "അടിയന്തിര കോൺടാക്റ്റുകൾ",
    sosAlertRecipients: "SOS അലേർട്ട് സ്വീകർത്താക്കൾ",
    addNewContact: "പുതിയ കോൺടാക്റ്റ് ചേർക്കുക",
    name: "പേര്",
    phone: "ഫോൺ",
    relation: "ബന്ധം",
    primary: "പ്രാഥമിക",
    language: "ഭാഷ",
    settings: "സെറ്റിംഗ്സ്",
    helpSupport: "സഹായവും പിന്തുണയും",
    logout: "ലോഗ് ഔട്ട്",
    tripPlanner: "യാത്രാ പ്ലാനർ",
    fromLocation: "ഇവിടെ നിന്ന്",
    destination: "ലക്ഷ്യസ്ഥാനം",
    budget: "ബജറ്റ്",
    days: "ദിവസങ്ങൾ",
    day: "ദിവസം",
    generateItinerary: "യാത്രാ പട്ടിക സൃഷ്ടിക്കുക",
    transportMode: "ഗതാഗത മോഡ്",
    stays: "താമസം",
    food: "ഭക്ഷണം",
    activities: "പ്രവർത്തനങ്ങൾ",
    buffer: "ബഫർ",
    total: "ആകെ",
    budgetBreakdown: "ബജറ്റ് വിശദാംശങ്ങൾ",
    voiceAssistant: "വോയ്‌സ് അസിസ്റ്റന്റ്",
    listeningCommands: "കമാൻഡുകൾ ശ്രദ്ധിക്കുന്നു...",
  },
  bn: {
    home: "হোম",
    explore: "অন্বেষণ",
    trips: "ভ্রমণ",
    profile: "প্রোফাইল",
    search: "অনুসন্ধান",
    filter: "ফিল্টার",
    cancel: "বাতিল",
    save: "সংরক্ষণ",
    add: "যোগ করুন",
    delete: "মুছুন",
    edit: "সম্পাদনা",
    back: "পিছনে",
    viewAll: "সব দেখুন",
    loading: "লোড হচ্ছে...",
    goodMorning: "সুপ্রভাত",
    goodAfternoon: "শুভ অপরাহ্ন",
    goodEvening: "শুভ সন্ধ্যা",
    traveler: "ভ্রমণকারী",
    whereExplore: "আজ কোথায় যেতে চান?",
    liveLocation: "লাইভ লোকেশন",
    sharingLocation: "আপনার লোকেশন শেয়ার হচ্ছে",
    locationOff: "লোকেশন বন্ধ",
    exploreCategories: "বিভাগ অন্বেষণ করুন",
    exploreMap: "মানচিত্র দেখুন",
    planTrip: "ভ্রমণ পরিকল্পনা",
    discover: "আবিষ্কার করুন",
    temples: "মন্দির",
    hospitals: "হাসপাতাল",
    emergency: "জরুরী",
    hiddenSpots: "লুকানো স্থান",
    hiddenSpotsDesc: "স্থানীয় রত্ন, অবাণিজ্যিক স্থান",
    transport: "পরিবহন",
    hostels: "হোস্টেল",
    attractions: "আকর্ষণ",
    sos: "SOS",
    tapForEmergency: "জরুরী অবস্থার জন্য ট্যাপ করুন",
    confirmEmergency: "জরুরী SOS নিশ্চিত করুন?",
    sendingAlert: "সতর্কতা পাঠানো হচ্ছে...",
    alertSent: "সতর্কতা পাঠানো হয়েছে!",
    sosDescription: "এটি আপনার লাইভ লোকেশন জরুরী সেবায় পাঠাবে।",
    sendSOS: "SOS পাঠান",
    booking: "বুকিং",
    bookNow: "এখনই বুক করুন",
    searchPlaces: "স্থান, আকর্ষণ অনুসন্ধান করুন...",
    priceRange: "মূল্য সীমা",
    rating: "রেটিং",
    distance: "দূরত্ব",
    sortBy: "সাজান",
    bestMatch: "সেরা মিল",
    cheapest: "সবচেয়ে সস্তা",
    safest: "সবচেয়ে নিরাপদ",
    nearestFirst: "নিকটতম প্রথমে",
    available: "উপলব্ধ",
    perNight: "প্রতি রাতে",
    perPerson: "প্রতি ব্যক্তি",
    viewOnMap: "মানচিত্রে দেখুন",
    listView: "তালিকা দৃশ্য",
    mapView: "মানচিত্র দৃশ্য",
    myProfile: "আমার প্রোফাইল",
    emergencyContacts: "জরুরী যোগাযোগ",
    sosAlertRecipients: "SOS সতর্কতা প্রাপক",
    addNewContact: "নতুন যোগাযোগ যোগ করুন",
    name: "নাম",
    phone: "ফোন",
    relation: "সম্পর্ক",
    primary: "প্রাথমিক",
    language: "ভাষা",
    settings: "সেটিংস",
    helpSupport: "সাহায্য ও সমর্থন",
    logout: "লগ আউট",
    tripPlanner: "ভ্রমণ পরিকল্পক",
    fromLocation: "থেকে",
    destination: "গন্তব্য",
    budget: "বাজেট",
    days: "দিন",
    day: "দিন",
    generateItinerary: "ভ্রমণসূচী তৈরি করুন",
    transportMode: "পরিবহন মোড",
    stays: "থাকার জায়গা",
    food: "খাবার",
    activities: "কার্যক্রম",
    buffer: "বাফার",
    total: "মোট",
    budgetBreakdown: "বাজেট বিশ্লেষণ",
    voiceAssistant: "ভয়েস সহকারী",
    listeningCommands: "কমান্ড শুনছে...",
  },
  mr: {
    home: "होम",
    explore: "शोधा",
    trips: "सहली",
    profile: "प्रोफाइल",
    search: "शोधा",
    filter: "फिल्टर",
    cancel: "रद्द करा",
    save: "जतन करा",
    add: "जोडा",
    delete: "हटवा",
    edit: "संपादित करा",
    back: "मागे",
    viewAll: "सर्व पहा",
    loading: "लोड होत आहे...",
    goodMorning: "सुप्रभात",
    goodAfternoon: "शुभ दुपार",
    goodEvening: "शुभ संध्याकाळ",
    traveler: "प्रवासी",
    whereExplore: "आज कुठे जायचे आहे?",
    liveLocation: "लाइव्ह लोकेशन",
    sharingLocation: "तुमचे लोकेशन शेअर होत आहे",
    locationOff: "लोकेशन बंद",
    exploreCategories: "श्रेण्या शोधा",
    exploreMap: "नकाशा पहा",
    planTrip: "सहल नियोजन",
    discover: "शोधा",
    temples: "मंदिरे",
    hospitals: "रुग्णालये",
    emergency: "आणीबाणी",
    hiddenSpots: "लपलेली ठिकाणे",
    hiddenSpotsDesc: "स्थानिक रत्ने, गैर-व्यावसायिक ठिकाणे",
    transport: "वाहतूक",
    hostels: "हॉस्टेल",
    attractions: "आकर्षणे",
    sos: "SOS",
    tapForEmergency: "आणीबाणीसाठी टॅप करा",
    confirmEmergency: "आणीबाणी SOS पुष्टी करा?",
    sendingAlert: "अलर्ट पाठवत आहे...",
    alertSent: "अलर्ट पाठवला!",
    sosDescription: "हे तुमचे लाइव्ह लोकेशन आणीबाणी सेवांना पाठवेल.",
    sendSOS: "SOS पाठवा",
    booking: "बुकिंग",
    bookNow: "आता बुक करा",
    searchPlaces: "ठिकाणे, आकर्षणे शोधा...",
    priceRange: "किंमत श्रेणी",
    rating: "रेटिंग",
    distance: "अंतर",
    sortBy: "क्रमवारी लावा",
    bestMatch: "सर्वोत्तम जुळणी",
    cheapest: "सर्वात स्वस्त",
    safest: "सर्वात सुरक्षित",
    nearestFirst: "जवळचे प्रथम",
    available: "उपलब्ध",
    perNight: "प्रति रात्र",
    perPerson: "प्रति व्यक्ती",
    viewOnMap: "नकाशावर पहा",
    listView: "यादी दृश्य",
    mapView: "नकाशा दृश्य",
    myProfile: "माझे प्रोफाइल",
    emergencyContacts: "आणीबाणी संपर्क",
    sosAlertRecipients: "SOS अलर्ट प्राप्तकर्ते",
    addNewContact: "नवीन संपर्क जोडा",
    name: "नाव",
    phone: "फोन",
    relation: "नाते",
    primary: "प्राथमिक",
    language: "भाषा",
    settings: "सेटिंग्स",
    helpSupport: "मदत आणि समर्थन",
    logout: "लॉग आउट",
    tripPlanner: "सहल नियोजक",
    fromLocation: "येथून",
    destination: "गंतव्य",
    budget: "बजेट",
    days: "दिवस",
    day: "दिवस",
    generateItinerary: "प्रवास मार्ग तयार करा",
    transportMode: "वाहतूक मोड",
    stays: "राहण्याची जागा",
    food: "अन्न",
    activities: "क्रियाकलाप",
    buffer: "बफर",
    total: "एकूण",
    budgetBreakdown: "बजेट तपशील",
    voiceAssistant: "व्हॉइस असिस्टंट",
    listeningCommands: "कमांड ऐकत आहे...",
  },
};

const languageNames: Record<Language, string> = {
  en: "English",
  hi: "हिंदी (Hindi)",
  ta: "தமிழ் (Tamil)",
  te: "తెలుగు (Telugu)",
  kn: "ಕನ್ನಡ (Kannada)",
  ml: "മലയാളം (Malayalam)",
  bn: "বাংলা (Bengali)",
  mr: "मराठी (Marathi)",
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: Translations;
  languageNames: Record<Language, string>;
  availableLanguages: Language[];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("en");

  const value: LanguageContextType = {
    language,
    setLanguage,
    t: translations[language],
    languageNames,
    availableLanguages: Object.keys(translations) as Language[],
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
