"""
Concatenate all seed SQL files into a single file for the Supabase SQL Editor.
Run this, then copy-paste the output into:
  https://supabase.com/dashboard/project/bqpkltznzkwvageimfic/sql
"""

import os

SUPABASE_DIR = r"d:\miniguide\supabase"
OUTPUT = os.path.join(SUPABASE_DIR, "seed_all_combined.sql")

SEED_ORDER = [
    "seed.sql",
    "seed_places.sql",
    "seed_temples.sql",
    "seed_hotels.sql",
    "seed_restaurants.sql",
    "seed_landmarks.sql",
    "seed_destinations.sql",
    "seed_transport.sql",
    "seed_rapido.sql",
    "seed_bus_routes.sql",
    "seed_bus_prices.sql",
    "seed_hospitals_india.sql",
    "seed_health_centres.sql",
    "seed_ride_intelligence.sql",
    "seed_osm_metro.sql",
    "seed_osm_police.sql",
    "seed_osm_fire.sql",
    "seed_osm_pharmacy.sql",
    "seed_osm_tourist.sql",
    "seed_osm_railway.sql",
    "seed_worship.sql",
    "seed_hidden_gems.sql",
]

HEADER = """-- ============================================================================
-- MINI GUDIE — COMPLETE SEED DATA
-- Generated by scripts/concat_seeds.py
-- Total: ~15,572 places across 18 categories
-- ============================================================================
-- INSTRUCTIONS:
-- 1. Open Supabase SQL Editor
-- 2. Paste this entire file
-- 3. Click "Run" (it may take a minute for large files)
-- ============================================================================

-- ── STEP 1: Expand the place_category enum ─────────────────────────────────
ALTER TYPE place_category ADD VALUE IF NOT EXISTS 'hotel';
ALTER TYPE place_category ADD VALUE IF NOT EXISTS 'restaurant';
ALTER TYPE place_category ADD VALUE IF NOT EXISTS 'landmark';
ALTER TYPE place_category ADD VALUE IF NOT EXISTS 'destination';
ALTER TYPE place_category ADD VALUE IF NOT EXISTS 'bus_route';
ALTER TYPE place_category ADD VALUE IF NOT EXISTS 'transport';
ALTER TYPE place_category ADD VALUE IF NOT EXISTS 'tourist';
ALTER TYPE place_category ADD VALUE IF NOT EXISTS 'metro';
ALTER TYPE place_category ADD VALUE IF NOT EXISTS 'police';
ALTER TYPE place_category ADD VALUE IF NOT EXISTS 'fire_station';
ALTER TYPE place_category ADD VALUE IF NOT EXISTS 'pharmacy';
ALTER TYPE place_category ADD VALUE IF NOT EXISTS 'railway';
ALTER TYPE place_category ADD VALUE IF NOT EXISTS 'health_centre';

"""


def main():
    parts = [HEADER]
    total_rows = 0

    for filename in SEED_ORDER:
        path = os.path.join(SUPABASE_DIR, filename)
        if not os.path.exists(path):
            print(f"  SKIP {filename} (not found)")
            continue

        with open(path, "r", encoding="utf-8") as f:
            content = f.read().strip()

        # Count VALUES rows (approximate)
        rows = content.count("  (") + content.count("  ('")
        total_rows += rows

        parts.append(f"\n-- ══════════════════════════════════════════════════════════\n")
        parts.append(f"-- FILE: {filename} (~{rows} rows)\n")
        parts.append(f"-- ══════════════════════════════════════════════════════════\n\n")
        parts.append(content)
        parts.append("\n")

        print(f"  Added {filename:<35} ~{rows:>5} rows")

    combined = "\n".join(parts)

    with open(OUTPUT, "w", encoding="utf-8") as f:
        f.write(combined)

    size_mb = os.path.getsize(OUTPUT) / 1024 / 1024
    print(f"\nSaved {OUTPUT}")
    print(f"  Size: {size_mb:.1f} MB")
    print(f"  Total rows: ~{total_rows:,}")
    print(f"\nNOTE: The Supabase SQL Editor may have a size limit.")
    print("For large files, split into batches or use the Supabase CLI:")
    print("  supabase db push")


if __name__ == "__main__":
    main()
